### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by floyd-fuh** [CoreyD97/Stepper#11]
If you could add a couple of simple lines of build instructions to the README to build the jar, that would be helpful. I'm not a gradle pro, but it seems that the parent directory will need your BurpExtenderUtilities. Then it built, but it seems that the GSON dependencies were still missing when I loaded the extension in Burp afterwards.

**Comment by CoreyD97** [comment]
Hey,

Sorry I should have wrapped the includeBuild statement in settings.gradle with an if statement to onlu include the files if they exist, that bit is just a helper for me to be able to work on BurpExtenderUtilities from within the Stepper project.

If you comment out lines 3-7 of settings.gradle, it'll download BurpExtenderUtilities as a library for you instead during the build process.

To build the project as a jar, there should be a task defined as either jar or fatJar within build.gradle . I'd check which it is for you but I'm afraid I'm on mobile at the minute.

To run this task just execute:  gradle fatJar (or gradle jar depending on the task name)

Ill update the readme to include full instructions when I can :blush:

Thanks,
Corey
