### ISSUE TITLE
Stepper generically breaks uploads

### ISSUE THREAD

**Issue by floyd-fuh** [CoreyD97/Stepper#12]
I've just had a very strange bug in Burp in a file upload functionality. When I uploaded a PNG file through Burp, the server received a corrupt image. It took me very long to figure it out, but without Burp it worked and at one point I realized by simply unloading the Stepper extension (version 1.2), the issue was gone.

Stepper seems to get a class cast wrong, very similar to what is described here: https://blog.gdssecurity.com/labs/2015/2/18/when-efbfbd-and-friends-come-knocking-observations-of-byte-a.html . So instead of a PNG I uploaded starting with the magic bytes \x89PNG, the server received \xEF\xBF\xBDPNG. Of course also for other bytes greater than 0x7f they were replaced by \xEF\xBF\xBD.

The biggest problem with this is actually that Stepper has this problem, although Stepper is not used at all in this case. So this is a *passive* issue of Stepper that occurs as soon as Stepper is loaded. So this must be a problem in the processHttp API that Stepper is hooking or similar. It is not visible in Logger++ or anything, so this won't be an easy one to debug. Additionally, this might be OS platform dependent as discussed in the above link.

Sad panda.

**Comment by CoreyD97** [comment]
Hi Floyd,

I've just realized I never published a build when I made the change but as of commit https://github.com/CoreyD97/Stepper/commit/29b4cdb359527a3498360822a9059a8c199abe2f, Stepper will only update messages which have had replacements made.

I have been able to reproduce the issue with the byte conversion though, so hopefully I can find some workaround to allow stepper to work on binary messages without any issues such as the above.

Thanks,
Corey
