### ISSUE TITLE
New Variable Types e.g. Static, Prompt

### ISSUE THREAD

**Issue by CoreyD97** [CoreyD97/Stepper#13]
Add the ability for variables to be different types. 
For example:
The static type will be defined by the user and left as is.
The prompt type will prompt the user to input a value at time of execution. This will be useful for things like one time passcodes etc.

**Comment by floyd-fuh** [comment]
while you are at it, it would be good to have something like random. Having a random UUID for example can be achieved by allowing random numbers

**Comment by CoreyD97** [comment]
Hey @floyd-fuh, I could implement something like that however it would be quite a lot of work as there's a ton of different ways the random numbers could be formatted etc, instead I'd recommend combining stepper with [Hackvertor](https://github.com/portswigger/hackvertor) for this kind of scenario :smile:
