### ISSUE TITLE
Visible time+size of response

### ISSUE THREAD

**Issue by Hipapheralkus** [CoreyD97/Stepper#18]
The repeater has great feature of showing the time of arrival and size of the response. Would it be possible to implement it here as well? For example, to discover chained time-based vulnerabilities, like enumeration of usernames in complex login scenarios.

**Comment by CoreyD97** [comment]
This is definitely something I can implement, I'll add it to the todo list!

**Comment by CoreyD97** [comment]
Hey!
Thanks again for the suggestion, I've implemented this just now. I'll be pushing a release with this and some of your other suggestions soon. :smiley:
