### ISSUE TITLE
Rearranging tabs

### ISSUE THREAD

**Issue by Hipapheralkus** [CoreyD97/Stepper#20]
If I make a sequence, and I want to rearrange it (for Execute Sequence to work), at the moment it doesn't seem possible. Would it be possible to add a feature to rearrange the order of tabs within the sequence? 
Thanks:)

**Comment by CoreyD97** [comment]
I definitely agree here, rearranging steps is a very useful feature.
I've added this to my todo list already :)

**Comment by CoreyD97** [comment]
Hey! I've been able to start implementing this recently.
At the moment I don't have the time to create a fancy drag and drop for the tabs, but tabs can now be right clicked and a new index selected to move them around. Hopefully this will do for now!

This will be included in the next release :)
