### ISSUE TITLE
Content-Length header does not update

### ISSUE THREAD

**Issue by CoreyD97** [CoreyD97/Stepper#23]
Content-Length header is not updated when sending a request.
Should also implement a toggle to disable this functionality.

**Comment by floyd-fuh** [comment]
Hi Corey,

I just updated to the latest git version, but for some reason the content-length still does not seem to update for requests properly. Is it possible that you do not set the content-length after the replacement of variables? The requests only work when I send them to the repeater which will then send a different content-length

**Comment by CoreyD97** [comment]
Hey, thanks for raising this. Looks like I rushed this and only implemented it for using variables in tools other than stepper (ironic, right?) 😄 

Just noticed another issue with my implementation because of this too, so I'll get working on that also!

**Comment by CoreyD97** [comment]
Should be fixed now, let me know if you have any issues after this :)

**Comment by floyd-fuh** [comment]
perfect, now it works :)
btw. you could also update the MessageView editor (like Repeater does) but that's just a gimmick, I'm fine with how it works at the moment

**Comment by CoreyD97** [comment]
Perfect thanks for checking! I've left a little TODO in the code for that too, maybe I'll add it at some point anyway just so people can see that it is updating :)
