### ISSUE TITLE
Stepper replacement and variables are not working in repeater.

### ISSUE THREAD

**Issue by NotSoEthical** [CoreyD97/Stepper#31]
### Variable issue
![burp](https://user-images.githubusercontent.com/16857976/91351399-e9dd8e80-e7f0-11ea-8f33-5f0183eca747.png)
The global and regex variables work only in stepper tab. When I try insert $VAR:variable_name$ to the request in repeater tab it does not replace. Request sending with $VAR:variable_name$ as in RAW request.

![burp2](https://user-images.githubusercontent.com/16857976/91352289-4ee5b400-e7f2-11ea-831e-85954e540400.png)
![burp3](https://user-images.githubusercontent.com/16857976/91352288-4e4d1d80-e7f2-11ea-820a-0b479b8ad612.png)
![burp4](https://user-images.githubusercontent.com/16857976/91352286-4d1bf080-e7f2-11ea-805b-209bf7f59b0b.png)
Where can be an issue?
Thank you.

**Comment by CoreyD97** [comment]
Hey! Sorry about this, I made some changes in the recent update as variables names could be repeated across different sequences.

Could you try using the context menu to reinsert the variables to your repeater request?

**Comment by NotSoEthical** [comment]
> Hey! Sorry about this, I made some changes in the recent update as variables names could be repeated across different sequences.


Actually no problem ;) 
Now I know that is just development feature :)

> 
> Could you try using the context menu to reinsert the variables to your repeater request?
I am only able to see the variable name from context menu but it does not work for inserting.
I am using latest Burp Suite 8.1 (for this date) version
and 
addon from BAPP store with update from 16 July 2020
![burp5](https://user-images.githubusercontent.com/16857976/91354697-c9640300-e7f5-11ea-98e5-ba94ca7c0d09.png)

Will wait for new update :)

**Comment by CoreyD97** [comment]
Selecting the entry in the context menu will not insert it into the request automatically as this isn't possible because of limitations with the Burp API, but should add it to the clipboard for you to paste in.

Alternatively, the help menu in Stepper should show the format for using variables in tools if I updated that correctly!

If not, I believe the format should be:
 `$VAR:SEQUENCENAME:VARIABLENAME$`

If you're still having issues let me know and I'll look into it for you.

**Comment by NotSoEthical** [comment]
Now I got.
Thank you so much for the quick reply.
![stepper_works](https://user-images.githubusercontent.com/16857976/91357438-e69ad080-e7f9-11ea-883a-5a88eab3559d.gif)

**Comment by CoreyD97** [comment]
No problem, happy to help! :+1:
