### ISSUE TITLE
Permanent ignore option for binary data replacement

### ISSUE THREAD

**Issue by irsdl** [CoreyD97/Stepper#38]
The following message does not have an ignore option
![image](https://user-images.githubusercontent.com/1798313/109977848-271d5e80-7cf5-11eb-8f17-12a2045f7a11.png)

Also maybe handle the binary data better when the change is not in the body but is in the header?

**Comment by CoreyD97** [comment]
Hey, I took a shot at replacing the String-based match and replace here with a [custom find+replace operating on the raw binary data](https://github.com/CoreyD97/Stepper/blob/master/src/main/java/com/coreyd97/stepper/util/ReplacingInputStream.java) so the corruption of binary data shouldn't be an issue anymore. Any chance you could give it a try please? You can get the build from [here](https://github.com/CoreyD97/Stepper/suites/3252107950/artifacts/75586974) (Note: you need to be logged into GitHub)



There's also a few other improvements etc I'm working on in that build, but still more to go! :)

**Comment by ganesh2183** [comment]
@CoreyD97 When i try to run the stepper login sequence through session handling rules adding header value "X-Stepper-Execute-Before: login" ,  Getting the error as

**The Request contains non UTF characters.
Stepper is able to male the replacements, but some of the binary data may be lost. Continue?**

How to fix this issue.

**Comment by C0DEbrained** [comment]
Please make sure you're using the latest release available on Github. If you still have this issue after that, open a new issue and I'll look into it for you.

**Comment by ganesh2183** [comment]
@CoreyD97 Currently i m using latest version(1.4.2) available in BApp store (07 Sep 2023). Please share the latest updated jar file to add into burp.

**Comment by C0DEbrained** [comment]
You can find the latest release here: https://github.com/CoreyD97/Stepper/releases/

**Comment by ganesh2183** [comment]
I tried with latest version(1.4.3) from https://github.com/CoreyD97/Stepper/releases/
Getting the same error:

**The Request contains non UTF characters.
Stepper is able to male the replacements, but some of the binary data may be lost. Continue?**

What would be non UTF characters?

**Comment by C0DEbrained** [comment]
This error hasn't been in the code for a few versions now. Please open a new issue and ill look into it.
