### ISSUE TITLE
Issue with Gradle in installing the latest version of Stepper

### ISSUE THREAD

**Issue by iamyuthan** [CoreyD97/Stepper#55]
> Could you please give this a try using the latest version and let me know if you're still having issues?
> 
> _Originally posted by @CoreyD97 in https://github.com/CoreyD97/Stepper/issues/53#issuecomment-982746498_

Hey @CoreyD97 ,

I have tried installing the latest version. It throws the following error, kindly let me know if I am doing anything wrong. I have given my Gradle build details as well in the screenshot below.

![image](https://user-images.githubusercontent.com/83505381/144820992-7637f448-6b71-4f19-a8e6-9518cc5a9b1f.png)

**Comment by iamyuthan** [comment]
Hey @CoreyD97 ,

I have found the fix by myself.
I have suggested the resolution here, #56 as it may help others.
Mean while I will verify if this version resolves #49

**Comment by CoreyD97** [comment]
Merged your pull request to fix this. Thanks again.
