### ISSUE TITLE
Importing the Stepper.jar to Burp has an issue

### ISSUE THREAD

**Issue by iamyuthan** [CoreyD97/Stepper#57]
_Originally posted by @CoreyD97 in https://github.com/CoreyD97/Stepper/issues/53#issuecomment-982746498_
https://github.com/CoreyD97/Stepper/issues/55#issuecomment-986614128

Hey @CoreyD97 ,

I am not able to import the JAR file to Burp as it throws the following errors. Kindly help me to resolve it.

![image](https://user-images.githubusercontent.com/83505381/144826782-f21ec68f-3487-4c21-bb06-0b92d799299f.png)

**Comment by CoreyD97** [comment]
That's interesting. I'm looking into this now.
